### ISSUE TITLE
How to allow for webpack-dev-server to allow entry points from react-router?

### ISSUE THREAD

**Issue by SudoPlz** [adjohu/marty-webpack-starter#3]
Hey Adam, I really like your starter kit. 
My problem is I'm not that experienced with webpack nor express and I'd love to be able to have express serve my page on any route.. Not just /, but all react routes defined on react-router. 
Would you be kind enough to help with that? 
I plan to use your starter kit, because I really liked it.. Allthough I do prefer npm scripts instead of code wherever I can.
Check this out if you have time : http://stackoverflow.com/questions/26203725/how-to-allow-for-webpack-dev-server-to-allow-entry-points-from-react-router

**Comment by adjohu** [comment]
`npm start` should be all you need. This project doesn't use express.
